title: "0xm0t0k0's Cryptography & CS lab"
description: "Notes on cryptography, algorithms, CTF write-ups, data structures and my journey into computer science. Plus some interesting intesection between art & hacking.\nMy real name is '9366b1d5923333c2671f1688f9a9170549061196a0aab291' (Hint: a mix of XOR, ROT13 & RC2) :3"
theme: jekyll-theme-hacker
markdown: kramdown
baseurl: ""
url: "https://0xm0t0k0.github.io"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
